### ISSUE TITLE
Issues with the options --wandb, --ns 48 --nv 12, and with the GPU version of torch

### ISSUE THREAD

**Issue by orli91** [HannesStark/FlowSite#3]
Amazing Job Hannes!

I tried to test the code with the linked packages installed via "pip", but there are some issues on some options:
1) Activating the -wandb option, it tells that wandb has to be inizialized first (I thought that it may expect a training step before inference from provided weights)
----
File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/marco/Scrivania/FlowSite/inference.py", line 75, in <module>
    main_function()
  File "/home/marco/Scrivania/FlowSite/inference.py", line 69, in main_function
    if args.wandb: wandb.log({'numel': numel, 'trainer/global_step': 0})
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/site-packages/wandb/sdk/lib/preinit.py", line 36, in preinit_wrapper
    raise wandb.Error(f"You must call wandb.init() before {name}()")
wandb.errors.Error: You must call wandb.init() before wandb.log()
----

2) The options --ns 48 and --nv 12 raised many model shape errors (i.e., "copying a param with shape torch.Size([128, 96]) from checkpoint, the shape in current model is torch.Size([128, 144])"). Using --ns 32 and --nv 8, as in the training script, solved the problem

3) The CUDA GPU is detected, but the following torch problem was raised:
----
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/marco/Scrivania/FlowSite/inference.py", line 76, in <module>
    main_function()
  File "/home/marco/Scrivania/FlowSite/inference.py", line 73, in main_function
    trainer.predict(model=model_module, dataloaders=predict_loader, ckpt_path=args.checkpoint)
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 865, in predict
    return call._call_and_handle_interrupt(
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 904, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1031, in _run_stage
    return self.predict_loop.run()
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/site-packages/lightning/pytorch/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/site-packages/lightning/pytorch/loops/prediction_loop.py", line 122, in run
    self._predict_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/site-packages/lightning/pytorch/loops/prediction_loop.py", line 250, in _predict_step
    predictions = call._call_strategy_hook(trainer, "predict_step", *step_args)
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 429, in predict_step
    return self.lightning_module.predict_step(*args, **kwargs)
  File "/home/marco/Scrivania/FlowSite/lightning_modules/flowsite_module.py", line 510, in predict_step
    designed_seqs.append([np.array(RESTYPES)[designed_seq.cpu().numpy()][torch.where(full_prot_bid == i)] for i in range(len(batch.pdb_id))])
  File "/home/marco/Scrivania/FlowSite/lightning_modules/flowsite_module.py", line 510, in <listcomp>
    designed_seqs.append([np.array(RESTYPES)[designed_seq.cpu().numpy()][torch.where(full_prot_bid == i)] for i in range(len(batch.pdb_id))])
File "/home/marco/miniconda3/envs/flowsite/lib/python3.10/site-packages/torch/_tensor.py", line 1030, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first
----
The CPU version of torch works fine

**Comment by HannesStark** [comment]
Thank you very much for the help!
1. I fixed the wandb issue.
2. I assume you used the different set of weights for this? Let me know if otherwise. I added a note that those parameters need to be changed as well.
3. Fixed.

**Comment by toilahung** [comment]
wandb issue still persists

**Comment by HannesStark** [comment]
Are you sure that is the same problem?
I would find that surprising since that line no longer exists and wandb is not only called inside the lightning module.

**Comment by toilahung** [comment]
Yes I pulled the latest from main. Here's the error:

`/home/hung/miniconda3/envs/flowsite/lib/python3.10/site-packages/torch/overrides.py:110: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  torch.has_cuda,
/home/hung/miniconda3/envs/flowsite/lib/python3.10/site-packages/torch/overrides.py:111: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  torch.has_cudnn,
/home/hung/miniconda3/envs/flowsite/lib/python3.10/site-packages/torch/overrides.py:117: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  torch.has_mps,
/home/hung/miniconda3/envs/flowsite/lib/python3.10/site-packages/torch/overrides.py:118: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  torch.has_mkldnn,
/home/hung/miniconda3/envs/flowsite/lib/python3.10/site-packages/torch/jit/_check.py:178: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
`Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(limit_test_batches=1.0)` was configured so 100% of the batches will be used..
[2023-11-05 12:59:16.328379] [DESKTOP-JL6RMMF] Model with 20149342 parameters
Traceback (most recent call last):
  File "/home/hung/miniconda3/envs/flowsite/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hung/miniconda3/envs/flowsite/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/etude/DL/FLowSite/inference.py", line 75, in <module>
    main_function()
  File "/mnt/c/Users/etude/DL/FLowSite/inference.py", line 69, in main_function
    if args.wandb: wandb.log({'numel': numel, 'trainer/global_step': 0})
  File "/home/hung/miniconda3/envs/flowsite/lib/python3.10/site-packages/wandb/sdk/lib/preinit.py", line 36, in preinit_wrapper
    raise wandb.Error(f"You must call wandb.init() before {name}()")
wandb.errors.Error: You must call wandb.init() before wandb.log()`

**Comment by HannesStark** [comment]
Ah thank you!
Should work now.

**Comment by orli91** [comment]
Dear Hannes,

I can confirm it now works without further issues and from what I am
testing this method seems to have a good performance also on
custom masked AF models docked with ligand susbtrates for which
there is no a PDB counterpart :).
